import type { components } from './schema'

export type Job = components['schemas']['JobResponse']
export type FileRecord = components['schemas']['FileResponse']
export type Analysis = components['schemas']['AnalysisResponse']
export type EntityWithMentions = components['schemas']['EntityWithMentions']
export type ReviewResult = components['schemas']['ReviewResponse']
export type TransformResult = components['schemas']['TransformResponse']
export type Verification = components['schemas']['VerificationResponse']
export type Certificate = components['schemas']['CertificateResponse']
export type AuditLedger = components['schemas']['AuditLedgerResponse']
export type Destruction = components['schemas']['DestructionResponse']
export type OfflineStatus = components['schemas']['OfflineStatusResponse']
export type ExposureGraph = components['schemas']['ExposureGraphResponse']
export type PrivacyRecommendation = components['schemas']['PrivacyRecommendationResponse']
export type AudienceProfile = components['schemas']['AudienceProfile']
export type PrivacyLevel = components['schemas']['PrivacyLevel']
export type GraphNode = components['schemas']['GraphNodeResponse']
export type GraphEdge = components['schemas']['GraphEdgeResponse']
