from enum import Enum, IntEnum


class FileType(str, Enum):
    PDF = "PDF"
    IMAGE = "IMAGE"
    TEXT = "TEXT"
    DATASET = "DATASET"
    DOCX = "DOCX"
    VIDEO = "VIDEO"


class EntityType(str, Enum):
    PHONE = "PHONE"
    EMAIL = "EMAIL"
    AADHAAR_LIKE = "AADHAAR_LIKE"
    PAN_LIKE = "PAN_LIKE"
    PERSON_NAME = "PERSON_NAME"
    PERSON_TITLE = "PERSON_TITLE"
    DATE_OF_BIRTH = "DATE_OF_BIRTH"
    GENERIC_DATE = "GENERIC_DATE"
    AGE = "AGE"
    STREET_ADDRESS = "STREET_ADDRESS"
    BUILDING_NUMBER = "BUILDING_NUMBER"
    LOCALITY = "LOCALITY"
    POSTCODE = "POSTCODE"
    EMPLOYER = "EMPLOYER"
    JOB_TITLE = "JOB_TITLE"
    CASE_REFERENCE = "CASE_REFERENCE"
    NATIONAL_ID = "NATIONAL_ID"
    PASSPORT_NUMBER = "PASSPORT_NUMBER"
    DRIVER_LICENSE_NUMBER = "DRIVER_LICENSE_NUMBER"
    TAX_IDENTIFIER = "TAX_IDENTIFIER"
    SOCIAL_IDENTIFIER = "SOCIAL_IDENTIFIER"
    PAYMENT_CARD_NUMBER = "PAYMENT_CARD_NUMBER"
    DEMOGRAPHIC_ATTRIBUTE = "DEMOGRAPHIC_ATTRIBUTE"
    FACE = "FACE"
    QR_CODE = "QR_CODE"
    SIGNATURE_CANDIDATE = "SIGNATURE_CANDIDATE"


class DetectionSource(str, Enum):
    TEXT_LAYER = "TEXT_LAYER"
    OCR = "OCR"
    VISUAL = "VISUAL"


class ReviewStatus(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    PROTECT = "PROTECT"
    IGNORE = "IGNORE"


class SensitivityLevel(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class TransformationType(str, Enum):
    MASK = "MASK"
    REMOVE_REGION = "REMOVE_REGION"
    GENERALIZE = "GENERALIZE"
    PSEUDONYMIZE = "PSEUDONYMIZE"
    SYNTHESIZE = "SYNTHESIZE"


class PrivacyLevel(IntEnum):
    DIRECT_MASKING = 1
    SENSITIVE_ENTITY_PROTECTION = 2
    CONTEXT_GENERALIZATION = 3
    RELATIONSHIP_SAFE_PSEUDONYMIZATION = 4
    SYNTHETIC_TWIN = 5


class AudienceProfile(str, Enum):
    PUBLIC_RELEASE = "PUBLIC_RELEASE"
    RESEARCH_PARTNER = "RESEARCH_PARTNER"
    INTERNAL_OPERATIONS = "INTERNAL_OPERATIONS"


class JobStatus(str, Enum):
    CREATED = "CREATED"
    UPLOADED = "UPLOADED"
    ANALYSED = "ANALYSED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    TRANSFORMED = "TRANSFORMED"
    VERIFIED = "VERIFIED"
    BLOCKED = "BLOCKED"
    DESTROYED = "DESTROYED"
    FAILED = "FAILED"


class OutputStatus(str, Enum):
    CREATED = "CREATED"
    VERIFIED_SAFE = "VERIFIED_SAFE"
    RELEASE_BLOCKED = "RELEASE_BLOCKED"
    DESTROYED = "DESTROYED"


class TestStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"


class GraphNodeKind(str, Enum):
    DOCUMENT = "DOCUMENT"
    SUBJECT = "SUBJECT"
    RELATED_PERSON = "RELATED_PERSON"
    DIRECT_IDENTIFIER = "DIRECT_IDENTIFIER"
    QUASI_IDENTIFIER = "QUASI_IDENTIFIER"
    VISUAL_IDENTIFIER = "VISUAL_IDENTIFIER"


class GraphEdgeType(str, Enum):
    CONTAINS = "CONTAINS"
    IDENTIFIES = "IDENTIFIES"
    DESCRIBES = "DESCRIBES"
    RELATED_TO = "RELATED_TO"
    CO_OCCURS_WITH = "CO_OCCURS_WITH"
